CREATE TABLE IF NOT EXISTS t_banks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(4) NOT NULL,
  name VARCHAR(100) NOT NULL,
  kana VARCHAR(100) NOT NULL,
  hira VARCHAR(100) NOT NULL,
  roma VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_branches (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bank_code VARCHAR(4) NOT NULL,
  code VARCHAR(4) NOT NULL,
  name VARCHAR(100) NOT NULL,
  kana VARCHAR(100) NOT NULL,
  hira VARCHAR(100) NOT NULL,
  roma VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);